// This file is auto-generated by @hey-api/openapi-ts

import { type Client, formDataBodySerializer, type Options as Options2, type TDataShape } from './client';
import { client } from './client.gen';
import type { GetApiV1AppointmentsData, GetApiV1AppointmentsResponses, GetApiV1AppointmentsServicesData, GetApiV1AppointmentsServicesResponses, GetApiV1AppointmentsTimeSlotsData, GetApiV1AppointmentsTimeSlotsResponses, GetApiV1DashboardData, GetApiV1DashboardResponses, GetApiV1NotificationsData, GetApiV1NotificationsResponses, GetApiV1NotificationsUnreadCountData, GetApiV1NotificationsUnreadCountResponses, GetApiV1PetsBreedsData, GetApiV1PetsBreedsResponses, GetApiV1PetsByIdCardData, GetApiV1PetsByIdCardPdfData, GetApiV1PetsByIdCardPdfResponses, GetApiV1PetsByIdCardResponses, GetApiV1PetsByIdData, GetApiV1PetsByIdResponses, GetApiV1PetsData, GetApiV1PetsResponses, GetApiV1ProfileData, GetApiV1ProfileResponses, PostApiSmsRelaySendData, PostApiSmsRelaySendResponses, PostApiV1AppointmentsBulkData, PostApiV1AppointmentsBulkResponses, PostApiV1AppointmentsByIdCancelData, PostApiV1AppointmentsByIdCancelResponses, PostApiV1AppointmentsData, PostApiV1AppointmentsResponses, PostApiV1AuthForgotPasswordData, PostApiV1AuthForgotPasswordResponses, PostApiV1AuthLoginData, PostApiV1AuthLoginResponses, PostApiV1AuthLogoutData, PostApiV1AuthLogoutResponses, PostApiV1AuthRefreshData, PostApiV1AuthRefreshResponses, PostApiV1AuthRegisterData, PostApiV1AuthRegisterResponses, PostApiV1AuthResetPasswordData, PostApiV1AuthResetPasswordResponses, PostApiV1AuthVerify2FaData, PostApiV1AuthVerify2FaResponses, PostApiV1PetsData, PostApiV1PetsResponses, PutApiV1NotificationsByIdReadData, PutApiV1NotificationsByIdReadResponses, PutApiV1NotificationsReadAllData, PutApiV1NotificationsReadAllResponses, PutApiV1PetsByIdData, PutApiV1PetsByIdResponses, PutApiV1ProfileData, PutApiV1ProfilePasswordData, PutApiV1ProfilePasswordResponses, PutApiV1ProfilePhotoData, PutApiV1ProfilePhotoResponses, PutApiV1ProfileResponses } from './types.gen';
import { zGetApiV1AppointmentsData, zGetApiV1AppointmentsServicesData, zGetApiV1AppointmentsTimeSlotsData, zGetApiV1DashboardData, zGetApiV1NotificationsData, zGetApiV1NotificationsUnreadCountData, zGetApiV1PetsBreedsData, zGetApiV1PetsByIdCardData, zGetApiV1PetsByIdCardPdfData, zGetApiV1PetsByIdData, zGetApiV1PetsData, zGetApiV1ProfileData, zPostApiSmsRelaySendData, zPostApiV1AppointmentsBulkData, zPostApiV1AppointmentsByIdCancelData, zPostApiV1AppointmentsData, zPostApiV1AuthForgotPasswordData, zPostApiV1AuthLoginData, zPostApiV1AuthLogoutData, zPostApiV1AuthRefreshData, zPostApiV1AuthRegisterData, zPostApiV1AuthResetPasswordData, zPostApiV1AuthVerify2FaData, zPostApiV1PetsData, zPutApiV1NotificationsByIdReadData, zPutApiV1NotificationsReadAllData, zPutApiV1PetsByIdData, zPutApiV1ProfileData, zPutApiV1ProfilePasswordData, zPutApiV1ProfilePhotoData } from './zod.gen';

export type Options<TData extends TDataShape = TDataShape, ThrowOnError extends boolean = boolean> = Options2<TData, ThrowOnError> & {
    /**
     * You can provide a client instance returned by `createClient()` instead of
     * individual options. This might be also useful if you want to implement a
     * custom client.
     */
    client?: Client;
    /**
     * You can pass arbitrary values through the `meta` object. This can be
     * used to access values that aren't defined as part of the SDK function.
     */
    meta?: Record<string, unknown>;
};

export class SmsRelay {
    public static postApiSmsRelaySend<ThrowOnError extends boolean = false>(options: Options<PostApiSmsRelaySendData, ThrowOnError>) {
        return (options.client ?? client).post<PostApiSmsRelaySendResponses, unknown, ThrowOnError>({
            requestValidator: async (data) => await zPostApiSmsRelaySendData.parseAsync(data),
            url: '/api/SmsRelay/send',
            ...options,
            headers: {
                'Content-Type': 'application/json',
                ...options.headers
            }
        });
    }
}

export class Appointments {
    public static getApiV1Appointments<ThrowOnError extends boolean = false>(options?: Options<GetApiV1AppointmentsData, ThrowOnError>) {
        return (options?.client ?? client).get<GetApiV1AppointmentsResponses, unknown, ThrowOnError>({
            requestValidator: async (data) => await zGetApiV1AppointmentsData.parseAsync(data),
            url: '/api/v1/appointments',
            ...options
        });
    }
    
    public static postApiV1Appointments<ThrowOnError extends boolean = false>(options: Options<PostApiV1AppointmentsData, ThrowOnError>) {
        return (options.client ?? client).post<PostApiV1AppointmentsResponses, unknown, ThrowOnError>({
            requestValidator: async (data) => await zPostApiV1AppointmentsData.parseAsync(data),
            url: '/api/v1/appointments',
            ...options,
            headers: {
                'Content-Type': 'application/json',
                ...options.headers
            }
        });
    }
    
    public static postApiV1AppointmentsBulk<ThrowOnError extends boolean = false>(options: Options<PostApiV1AppointmentsBulkData, ThrowOnError>) {
        return (options.client ?? client).post<PostApiV1AppointmentsBulkResponses, unknown, ThrowOnError>({
            requestValidator: async (data) => await zPostApiV1AppointmentsBulkData.parseAsync(data),
            url: '/api/v1/appointments/bulk',
            ...options,
            headers: {
                'Content-Type': 'application/json',
                ...options.headers
            }
        });
    }
    
    public static postApiV1AppointmentsByIdCancel<ThrowOnError extends boolean = false>(options: Options<PostApiV1AppointmentsByIdCancelData, ThrowOnError>) {
        return (options.client ?? client).post<PostApiV1AppointmentsByIdCancelResponses, unknown, ThrowOnError>({
            requestValidator: async (data) => await zPostApiV1AppointmentsByIdCancelData.parseAsync(data),
            url: '/api/v1/appointments/{id}/cancel',
            ...options
        });
    }
    
    public static getApiV1AppointmentsTimeSlots<ThrowOnError extends boolean = false>(options?: Options<GetApiV1AppointmentsTimeSlotsData, ThrowOnError>) {
        return (options?.client ?? client).get<GetApiV1AppointmentsTimeSlotsResponses, unknown, ThrowOnError>({
            requestValidator: async (data) => await zGetApiV1AppointmentsTimeSlotsData.parseAsync(data),
            url: '/api/v1/appointments/time-slots',
            ...options
        });
    }
    
    public static getApiV1AppointmentsServices<ThrowOnError extends boolean = false>(options?: Options<GetApiV1AppointmentsServicesData, ThrowOnError>) {
        return (options?.client ?? client).get<GetApiV1AppointmentsServicesResponses, unknown, ThrowOnError>({
            requestValidator: async (data) => await zGetApiV1AppointmentsServicesData.parseAsync(data),
            url: '/api/v1/appointments/services',
            ...options
        });
    }
}

export class Auth {
    public static postApiV1AuthLogin<ThrowOnError extends boolean = false>(options: Options<PostApiV1AuthLoginData, ThrowOnError>) {
        return (options.client ?? client).post<PostApiV1AuthLoginResponses, unknown, ThrowOnError>({
            requestValidator: async (data) => await zPostApiV1AuthLoginData.parseAsync(data),
            url: '/api/v1/auth/login',
            ...options,
            headers: {
                'Content-Type': 'application/json',
                ...options.headers
            }
        });
    }
    
    public static postApiV1AuthVerify2Fa<ThrowOnError extends boolean = false>(options: Options<PostApiV1AuthVerify2FaData, ThrowOnError>) {
        return (options.client ?? client).post<PostApiV1AuthVerify2FaResponses, unknown, ThrowOnError>({
            requestValidator: async (data) => await zPostApiV1AuthVerify2FaData.parseAsync(data),
            url: '/api/v1/auth/verify-2fa',
            ...options,
            headers: {
                'Content-Type': 'application/json',
                ...options.headers
            }
        });
    }
    
    public static postApiV1AuthRegister<ThrowOnError extends boolean = false>(options: Options<PostApiV1AuthRegisterData, ThrowOnError>) {
        return (options.client ?? client).post<PostApiV1AuthRegisterResponses, unknown, ThrowOnError>({
            requestValidator: async (data) => await zPostApiV1AuthRegisterData.parseAsync(data),
            url: '/api/v1/auth/register',
            ...options,
            headers: {
                'Content-Type': 'application/json',
                ...options.headers
            }
        });
    }
    
    public static postApiV1AuthRefresh<ThrowOnError extends boolean = false>(options: Options<PostApiV1AuthRefreshData, ThrowOnError>) {
        return (options.client ?? client).post<PostApiV1AuthRefreshResponses, unknown, ThrowOnError>({
            requestValidator: async (data) => await zPostApiV1AuthRefreshData.parseAsync(data),
            url: '/api/v1/auth/refresh',
            ...options,
            headers: {
                'Content-Type': 'application/json',
                ...options.headers
            }
        });
    }
    
    public static postApiV1AuthLogout<ThrowOnError extends boolean = false>(options: Options<PostApiV1AuthLogoutData, ThrowOnError>) {
        return (options.client ?? client).post<PostApiV1AuthLogoutResponses, unknown, ThrowOnError>({
            requestValidator: async (data) => await zPostApiV1AuthLogoutData.parseAsync(data),
            url: '/api/v1/auth/logout',
            ...options,
            headers: {
                'Content-Type': 'application/json',
                ...options.headers
            }
        });
    }
    
    public static postApiV1AuthForgotPassword<ThrowOnError extends boolean = false>(options: Options<PostApiV1AuthForgotPasswordData, ThrowOnError>) {
        return (options.client ?? client).post<PostApiV1AuthForgotPasswordResponses, unknown, ThrowOnError>({
            requestValidator: async (data) => await zPostApiV1AuthForgotPasswordData.parseAsync(data),
            url: '/api/v1/auth/forgot-password',
            ...options,
            headers: {
                'Content-Type': 'application/json',
                ...options.headers
            }
        });
    }
    
    public static postApiV1AuthResetPassword<ThrowOnError extends boolean = false>(options: Options<PostApiV1AuthResetPasswordData, ThrowOnError>) {
        return (options.client ?? client).post<PostApiV1AuthResetPasswordResponses, unknown, ThrowOnError>({
            requestValidator: async (data) => await zPostApiV1AuthResetPasswordData.parseAsync(data),
            url: '/api/v1/auth/reset-password',
            ...options,
            headers: {
                'Content-Type': 'application/json',
                ...options.headers
            }
        });
    }
}

export class Dashboard {
    public static getApiV1Dashboard<ThrowOnError extends boolean = false>(options?: Options<GetApiV1DashboardData, ThrowOnError>) {
        return (options?.client ?? client).get<GetApiV1DashboardResponses, unknown, ThrowOnError>({
            requestValidator: async (data) => await zGetApiV1DashboardData.parseAsync(data),
            url: '/api/v1/dashboard',
            ...options
        });
    }
}

export class Notifications {
    public static getApiV1Notifications<ThrowOnError extends boolean = false>(options?: Options<GetApiV1NotificationsData, ThrowOnError>) {
        return (options?.client ?? client).get<GetApiV1NotificationsResponses, unknown, ThrowOnError>({
            requestValidator: async (data) => await zGetApiV1NotificationsData.parseAsync(data),
            url: '/api/v1/notifications',
            ...options
        });
    }
    
    public static getApiV1NotificationsUnreadCount<ThrowOnError extends boolean = false>(options?: Options<GetApiV1NotificationsUnreadCountData, ThrowOnError>) {
        return (options?.client ?? client).get<GetApiV1NotificationsUnreadCountResponses, unknown, ThrowOnError>({
            requestValidator: async (data) => await zGetApiV1NotificationsUnreadCountData.parseAsync(data),
            url: '/api/v1/notifications/unread-count',
            ...options
        });
    }
    
    public static putApiV1NotificationsByIdRead<ThrowOnError extends boolean = false>(options: Options<PutApiV1NotificationsByIdReadData, ThrowOnError>) {
        return (options.client ?? client).put<PutApiV1NotificationsByIdReadResponses, unknown, ThrowOnError>({
            requestValidator: async (data) => await zPutApiV1NotificationsByIdReadData.parseAsync(data),
            url: '/api/v1/notifications/{id}/read',
            ...options
        });
    }
    
    public static putApiV1NotificationsReadAll<ThrowOnError extends boolean = false>(options?: Options<PutApiV1NotificationsReadAllData, ThrowOnError>) {
        return (options?.client ?? client).put<PutApiV1NotificationsReadAllResponses, unknown, ThrowOnError>({
            requestValidator: async (data) => await zPutApiV1NotificationsReadAllData.parseAsync(data),
            url: '/api/v1/notifications/read-all',
            ...options
        });
    }
}

export class Pets {
    public static getApiV1Pets<ThrowOnError extends boolean = false>(options?: Options<GetApiV1PetsData, ThrowOnError>) {
        return (options?.client ?? client).get<GetApiV1PetsResponses, unknown, ThrowOnError>({
            requestValidator: async (data) => await zGetApiV1PetsData.parseAsync(data),
            url: '/api/v1/pets',
            ...options
        });
    }
    
    public static postApiV1Pets<ThrowOnError extends boolean = false>(options: Options<PostApiV1PetsData, ThrowOnError>) {
        return (options.client ?? client).post<PostApiV1PetsResponses, unknown, ThrowOnError>({
            ...formDataBodySerializer,
            requestValidator: async (data) => await zPostApiV1PetsData.parseAsync(data),
            url: '/api/v1/pets',
            ...options,
            headers: {
                'Content-Type': null,
                ...options.headers
            }
        });
    }
    
    public static getApiV1PetsById<ThrowOnError extends boolean = false>(options: Options<GetApiV1PetsByIdData, ThrowOnError>) {
        return (options.client ?? client).get<GetApiV1PetsByIdResponses, unknown, ThrowOnError>({
            requestValidator: async (data) => await zGetApiV1PetsByIdData.parseAsync(data),
            url: '/api/v1/pets/{id}',
            ...options
        });
    }
    
    public static putApiV1PetsById<ThrowOnError extends boolean = false>(options: Options<PutApiV1PetsByIdData, ThrowOnError>) {
        return (options.client ?? client).put<PutApiV1PetsByIdResponses, unknown, ThrowOnError>({
            ...formDataBodySerializer,
            requestValidator: async (data) => await zPutApiV1PetsByIdData.parseAsync(data),
            url: '/api/v1/pets/{id}',
            ...options,
            headers: {
                'Content-Type': null,
                ...options.headers
            }
        });
    }
    
    public static getApiV1PetsBreeds<ThrowOnError extends boolean = false>(options?: Options<GetApiV1PetsBreedsData, ThrowOnError>) {
        return (options?.client ?? client).get<GetApiV1PetsBreedsResponses, unknown, ThrowOnError>({
            requestValidator: async (data) => await zGetApiV1PetsBreedsData.parseAsync(data),
            url: '/api/v1/pets/breeds',
            ...options
        });
    }
    
    public static getApiV1PetsByIdCard<ThrowOnError extends boolean = false>(options: Options<GetApiV1PetsByIdCardData, ThrowOnError>) {
        return (options.client ?? client).get<GetApiV1PetsByIdCardResponses, unknown, ThrowOnError>({
            requestValidator: async (data) => await zGetApiV1PetsByIdCardData.parseAsync(data),
            url: '/api/v1/pets/{id}/card',
            ...options
        });
    }
    
    public static getApiV1PetsByIdCardPdf<ThrowOnError extends boolean = false>(options: Options<GetApiV1PetsByIdCardPdfData, ThrowOnError>) {
        return (options.client ?? client).get<GetApiV1PetsByIdCardPdfResponses, unknown, ThrowOnError>({
            requestValidator: async (data) => await zGetApiV1PetsByIdCardPdfData.parseAsync(data),
            url: '/api/v1/pets/{id}/card/pdf',
            ...options
        });
    }
}

export class Profile {
    public static getApiV1Profile<ThrowOnError extends boolean = false>(options?: Options<GetApiV1ProfileData, ThrowOnError>) {
        return (options?.client ?? client).get<GetApiV1ProfileResponses, unknown, ThrowOnError>({
            requestValidator: async (data) => await zGetApiV1ProfileData.parseAsync(data),
            url: '/api/v1/profile',
            ...options
        });
    }
    
    public static putApiV1Profile<ThrowOnError extends boolean = false>(options: Options<PutApiV1ProfileData, ThrowOnError>) {
        return (options.client ?? client).put<PutApiV1ProfileResponses, unknown, ThrowOnError>({
            requestValidator: async (data) => await zPutApiV1ProfileData.parseAsync(data),
            url: '/api/v1/profile',
            ...options,
            headers: {
                'Content-Type': 'application/json',
                ...options.headers
            }
        });
    }
    
    public static putApiV1ProfilePassword<ThrowOnError extends boolean = false>(options: Options<PutApiV1ProfilePasswordData, ThrowOnError>) {
        return (options.client ?? client).put<PutApiV1ProfilePasswordResponses, unknown, ThrowOnError>({
            requestValidator: async (data) => await zPutApiV1ProfilePasswordData.parseAsync(data),
            url: '/api/v1/profile/password',
            ...options,
            headers: {
                'Content-Type': 'application/json',
                ...options.headers
            }
        });
    }
    
    public static putApiV1ProfilePhoto<ThrowOnError extends boolean = false>(options: Options<PutApiV1ProfilePhotoData, ThrowOnError>) {
        return (options.client ?? client).put<PutApiV1ProfilePhotoResponses, unknown, ThrowOnError>({
            ...formDataBodySerializer,
            requestValidator: async (data) => await zPutApiV1ProfilePhotoData.parseAsync(data),
            url: '/api/v1/profile/photo',
            ...options,
            headers: {
                'Content-Type': null,
                ...options.headers
            }
        });
    }
}
