// This file is auto-generated by @hey-api/openapi-ts

export type ClientOptions = {
    baseURL: 'https://localhost:7055' | 'http://localhost:5090' | (string & {});
};

export type BulkAppointmentItemRequest = {
    petId: number;
    categoryId: number;
    subtypeId?: number | null;
    appointmentDate: string;
    appointmentTime: string;
    notes?: string | null;
};

export type ChangePasswordRequest = {
    currentPassword: string;
    newPassword: string;
    confirmPassword: string;
};

export type CreateAppointmentRequest = {
    petId: number;
    categoryId: number;
    subtypeId?: number | null;
    appointmentDate: string;
    appointmentTime: string;
    notes?: string | null;
};

export type CreateBulkAppointmentRequest = {
    appointments: Array<BulkAppointmentItemRequest>;
};

export type ForgotPasswordRequest = {
    email: string;
};

export type IFormFile = Blob | File;

export type LoginRequest = {
    email: string;
    password: string;
    deviceInfo?: string | null;
};

export type RefreshTokenRequest = {
    refreshToken: string;
};

export type RegisterRequest = {
    firstName: string;
    lastName: string;
    email: string;
    phone: string;
    password: string;
    confirmPassword: string;
};

export type ResetPasswordRequest = {
    token: string;
    newPassword: string;
    confirmPassword: string;
};

export type UpdateProfileRequest = {
    firstName: string;
    lastName: string;
    phone: string;
};

export type Verify2FaRequest = {
    userId: number;
    code: string;
    deviceInfo?: string | null;
};

export type PostApiSmsRelaySendData = {
    body: unknown;
    path?: never;
    query?: never;
    url: '/api/SmsRelay/send';
};

export type PostApiSmsRelaySendResponses = {
    /**
     * OK
     */
    200: unknown;
};

export type GetApiV1AppointmentsData = {
    body?: never;
    path?: never;
    query?: never;
    url: '/api/v1/appointments';
};

export type GetApiV1AppointmentsResponses = {
    /**
     * OK
     */
    200: unknown;
};

export type PostApiV1AppointmentsData = {
    body: CreateAppointmentRequest;
    path?: never;
    query?: never;
    url: '/api/v1/appointments';
};

export type PostApiV1AppointmentsResponses = {
    /**
     * OK
     */
    200: unknown;
};

export type PostApiV1AppointmentsBulkData = {
    body: CreateBulkAppointmentRequest;
    path?: never;
    query?: never;
    url: '/api/v1/appointments/bulk';
};

export type PostApiV1AppointmentsBulkResponses = {
    /**
     * OK
     */
    200: unknown;
};

export type PostApiV1AppointmentsByIdCancelData = {
    body?: never;
    path: {
        id: number;
    };
    query?: never;
    url: '/api/v1/appointments/{id}/cancel';
};

export type PostApiV1AppointmentsByIdCancelResponses = {
    /**
     * OK
     */
    200: unknown;
};

export type GetApiV1AppointmentsTimeSlotsData = {
    body?: never;
    path?: never;
    query?: {
        date?: string;
    };
    url: '/api/v1/appointments/time-slots';
};

export type GetApiV1AppointmentsTimeSlotsResponses = {
    /**
     * OK
     */
    200: unknown;
};

export type GetApiV1AppointmentsServicesData = {
    body?: never;
    path?: never;
    query?: never;
    url: '/api/v1/appointments/services';
};

export type GetApiV1AppointmentsServicesResponses = {
    /**
     * OK
     */
    200: unknown;
};

export type PostApiV1AuthLoginData = {
    body: LoginRequest;
    path?: never;
    query?: never;
    url: '/api/v1/auth/login';
};

export type PostApiV1AuthLoginResponses = {
    /**
     * OK
     */
    200: unknown;
};

export type PostApiV1AuthVerify2FaData = {
    body: Verify2FaRequest;
    path?: never;
    query?: never;
    url: '/api/v1/auth/verify-2fa';
};

export type PostApiV1AuthVerify2FaResponses = {
    /**
     * OK
     */
    200: unknown;
};

export type PostApiV1AuthRegisterData = {
    body: RegisterRequest;
    path?: never;
    query?: never;
    url: '/api/v1/auth/register';
};

export type PostApiV1AuthRegisterResponses = {
    /**
     * OK
     */
    200: unknown;
};

export type PostApiV1AuthRefreshData = {
    body: RefreshTokenRequest;
    path?: never;
    query?: never;
    url: '/api/v1/auth/refresh';
};

export type PostApiV1AuthRefreshResponses = {
    /**
     * OK
     */
    200: unknown;
};

export type PostApiV1AuthLogoutData = {
    body: RefreshTokenRequest;
    path?: never;
    query?: never;
    url: '/api/v1/auth/logout';
};

export type PostApiV1AuthLogoutResponses = {
    /**
     * OK
     */
    200: unknown;
};

export type PostApiV1AuthForgotPasswordData = {
    body: ForgotPasswordRequest;
    path?: never;
    query?: never;
    url: '/api/v1/auth/forgot-password';
};

export type PostApiV1AuthForgotPasswordResponses = {
    /**
     * OK
     */
    200: unknown;
};

export type PostApiV1AuthResetPasswordData = {
    body: ResetPasswordRequest;
    path?: never;
    query?: never;
    url: '/api/v1/auth/reset-password';
};

export type PostApiV1AuthResetPasswordResponses = {
    /**
     * OK
     */
    200: unknown;
};

export type GetApiV1DashboardData = {
    body?: never;
    path?: never;
    query?: never;
    url: '/api/v1/dashboard';
};

export type GetApiV1DashboardResponses = {
    /**
     * OK
     */
    200: unknown;
};

export type GetApiV1NotificationsData = {
    body?: never;
    path?: never;
    query?: {
        typeFilter?: string;
        statusFilter?: string;
        search?: string;
        page?: number;
        pageSize?: number;
    };
    url: '/api/v1/notifications';
};

export type GetApiV1NotificationsResponses = {
    /**
     * OK
     */
    200: unknown;
};

export type GetApiV1NotificationsUnreadCountData = {
    body?: never;
    path?: never;
    query?: never;
    url: '/api/v1/notifications/unread-count';
};

export type GetApiV1NotificationsUnreadCountResponses = {
    /**
     * OK
     */
    200: unknown;
};

export type PutApiV1NotificationsByIdReadData = {
    body?: never;
    path: {
        id: number;
    };
    query?: never;
    url: '/api/v1/notifications/{id}/read';
};

export type PutApiV1NotificationsByIdReadResponses = {
    /**
     * OK
     */
    200: unknown;
};

export type PutApiV1NotificationsReadAllData = {
    body?: never;
    path?: never;
    query?: never;
    url: '/api/v1/notifications/read-all';
};

export type PutApiV1NotificationsReadAllResponses = {
    /**
     * OK
     */
    200: unknown;
};

export type GetApiV1PetsData = {
    body?: never;
    path?: never;
    query?: never;
    url: '/api/v1/pets';
};

export type GetApiV1PetsResponses = {
    /**
     * OK
     */
    200: unknown;
};

export type PostApiV1PetsData = {
    body: {
        Name?: string;
        Type?: string;
        Breed?: string;
        Birthdate?: string;
        Photo?: IFormFile;
    };
    path?: never;
    query?: never;
    url: '/api/v1/pets';
};

export type PostApiV1PetsResponses = {
    /**
     * OK
     */
    200: unknown;
};

export type GetApiV1PetsByIdData = {
    body?: never;
    path: {
        id: number;
    };
    query?: {
        page?: number;
        pageSize?: number;
        search?: string;
        categoryFilter?: number;
    };
    url: '/api/v1/pets/{id}';
};

export type GetApiV1PetsByIdResponses = {
    /**
     * OK
     */
    200: unknown;
};

export type PutApiV1PetsByIdData = {
    body: {
        Name?: string;
        Type?: string;
        Breed?: string;
        Birthdate?: string;
        Photo?: IFormFile;
    };
    path: {
        id: number;
    };
    query?: never;
    url: '/api/v1/pets/{id}';
};

export type PutApiV1PetsByIdResponses = {
    /**
     * OK
     */
    200: unknown;
};

export type GetApiV1PetsBreedsData = {
    body?: never;
    path?: never;
    query?: {
        type?: string;
    };
    url: '/api/v1/pets/breeds';
};

export type GetApiV1PetsBreedsResponses = {
    /**
     * OK
     */
    200: unknown;
};

export type GetApiV1PetsByIdCardData = {
    body?: never;
    path: {
        id: number;
    };
    query?: {
        page?: number;
        pageSize?: number;
    };
    url: '/api/v1/pets/{id}/card';
};

export type GetApiV1PetsByIdCardResponses = {
    /**
     * OK
     */
    200: unknown;
};

export type GetApiV1PetsByIdCardPdfData = {
    body?: never;
    path: {
        id: number;
    };
    query?: never;
    url: '/api/v1/pets/{id}/card/pdf';
};

export type GetApiV1PetsByIdCardPdfResponses = {
    /**
     * OK
     */
    200: unknown;
};

export type GetApiV1ProfileData = {
    body?: never;
    path?: never;
    query?: never;
    url: '/api/v1/profile';
};

export type GetApiV1ProfileResponses = {
    /**
     * OK
     */
    200: unknown;
};

export type PutApiV1ProfileData = {
    body: UpdateProfileRequest;
    path?: never;
    query?: never;
    url: '/api/v1/profile';
};

export type PutApiV1ProfileResponses = {
    /**
     * OK
     */
    200: unknown;
};

export type PutApiV1ProfilePasswordData = {
    body: ChangePasswordRequest;
    path?: never;
    query?: never;
    url: '/api/v1/profile/password';
};

export type PutApiV1ProfilePasswordResponses = {
    /**
     * OK
     */
    200: unknown;
};

export type PutApiV1ProfilePhotoData = {
    body: {
        photo?: IFormFile;
    };
    path?: never;
    query?: never;
    url: '/api/v1/profile/photo';
};

export type PutApiV1ProfilePhotoResponses = {
    /**
     * OK
     */
    200: unknown;
};
