// This file is auto-generated by @hey-api/openapi-ts

import * as z from 'zod';

export const zBulkAppointmentItemRequest = z.object({
    petId: z.int().min(-2147483648, { error: 'Invalid value: Expected int32 to be >= -2147483648' }).max(2147483647, { error: 'Invalid value: Expected int32 to be <= 2147483647' }),
    categoryId: z.int().min(-2147483648, { error: 'Invalid value: Expected int32 to be >= -2147483648' }).max(2147483647, { error: 'Invalid value: Expected int32 to be <= 2147483647' }),
    subtypeId: z.optional(z.union([
        z.int().min(-2147483648, { error: 'Invalid value: Expected int32 to be >= -2147483648' }).max(2147483647, { error: 'Invalid value: Expected int32 to be <= 2147483647' }),
        z.null()
    ])),
    appointmentDate: z.iso.datetime(),
    appointmentTime: z.string(),
    notes: z.optional(z.union([
        z.string(),
        z.null()
    ]))
});

export const zChangePasswordRequest = z.object({
    currentPassword: z.string(),
    newPassword: z.string().min(8),
    confirmPassword: z.string()
});

export const zCreateAppointmentRequest = z.object({
    petId: z.int().min(-2147483648, { error: 'Invalid value: Expected int32 to be >= -2147483648' }).max(2147483647, { error: 'Invalid value: Expected int32 to be <= 2147483647' }),
    categoryId: z.int().min(-2147483648, { error: 'Invalid value: Expected int32 to be >= -2147483648' }).max(2147483647, { error: 'Invalid value: Expected int32 to be <= 2147483647' }),
    subtypeId: z.optional(z.union([
        z.int().min(-2147483648, { error: 'Invalid value: Expected int32 to be >= -2147483648' }).max(2147483647, { error: 'Invalid value: Expected int32 to be <= 2147483647' }),
        z.null()
    ])),
    appointmentDate: z.iso.datetime(),
    appointmentTime: z.string(),
    notes: z.optional(z.union([
        z.string(),
        z.null()
    ]))
});

export const zCreateBulkAppointmentRequest = z.object({
    appointments: z.array(zBulkAppointmentItemRequest).min(1)
});

export const zForgotPasswordRequest = z.object({
    email: z.string()
});

export const zIFormFile = z.string();

export const zLoginRequest = z.object({
    email: z.string(),
    password: z.string(),
    deviceInfo: z.optional(z.union([
        z.string(),
        z.null()
    ]))
});

export const zRefreshTokenRequest = z.object({
    refreshToken: z.string()
});

export const zRegisterRequest = z.object({
    firstName: z.string().min(0).max(50),
    lastName: z.string().min(0).max(50),
    email: z.string(),
    phone: z.string().regex(/^\d{11}$/),
    password: z.string().min(8),
    confirmPassword: z.string()
});

export const zResetPasswordRequest = z.object({
    token: z.string(),
    newPassword: z.string().min(8),
    confirmPassword: z.string()
});

export const zUpdateProfileRequest = z.object({
    firstName: z.string().min(0).max(50),
    lastName: z.string().min(0).max(50),
    phone: z.string().regex(/^\d{11}$/)
});

export const zVerify2FaRequest = z.object({
    userId: z.int().min(-2147483648, { error: 'Invalid value: Expected int32 to be >= -2147483648' }).max(2147483647, { error: 'Invalid value: Expected int32 to be <= 2147483647' }),
    code: z.string().length(6),
    deviceInfo: z.optional(z.union([
        z.string(),
        z.null()
    ]))
});

export const zPostApiSmsRelaySendData = z.object({
    body: z.unknown(),
    path: z.optional(z.never()),
    query: z.optional(z.never())
});

export const zGetApiV1AppointmentsData = z.object({
    body: z.optional(z.never()),
    path: z.optional(z.never()),
    query: z.optional(z.never())
});

export const zPostApiV1AppointmentsData = z.object({
    body: zCreateAppointmentRequest,
    path: z.optional(z.never()),
    query: z.optional(z.never())
});

export const zPostApiV1AppointmentsBulkData = z.object({
    body: zCreateBulkAppointmentRequest,
    path: z.optional(z.never()),
    query: z.optional(z.never())
});

export const zPostApiV1AppointmentsByIdCancelData = z.object({
    body: z.optional(z.never()),
    path: z.object({
        id: z.int().min(-2147483648, { error: 'Invalid value: Expected int32 to be >= -2147483648' }).max(2147483647, { error: 'Invalid value: Expected int32 to be <= 2147483647' })
    }),
    query: z.optional(z.never())
});

export const zGetApiV1AppointmentsTimeSlotsData = z.object({
    body: z.optional(z.never()),
    path: z.optional(z.never()),
    query: z.optional(z.object({
        date: z.optional(z.iso.datetime())
    }))
});

export const zGetApiV1AppointmentsServicesData = z.object({
    body: z.optional(z.never()),
    path: z.optional(z.never()),
    query: z.optional(z.never())
});

export const zPostApiV1AuthLoginData = z.object({
    body: zLoginRequest,
    path: z.optional(z.never()),
    query: z.optional(z.never())
});

export const zPostApiV1AuthVerify2FaData = z.object({
    body: zVerify2FaRequest,
    path: z.optional(z.never()),
    query: z.optional(z.never())
});

export const zPostApiV1AuthRegisterData = z.object({
    body: zRegisterRequest,
    path: z.optional(z.never()),
    query: z.optional(z.never())
});

export const zPostApiV1AuthRefreshData = z.object({
    body: zRefreshTokenRequest,
    path: z.optional(z.never()),
    query: z.optional(z.never())
});

export const zPostApiV1AuthLogoutData = z.object({
    body: zRefreshTokenRequest,
    path: z.optional(z.never()),
    query: z.optional(z.never())
});

export const zPostApiV1AuthForgotPasswordData = z.object({
    body: zForgotPasswordRequest,
    path: z.optional(z.never()),
    query: z.optional(z.never())
});

export const zPostApiV1AuthResetPasswordData = z.object({
    body: zResetPasswordRequest,
    path: z.optional(z.never()),
    query: z.optional(z.never())
});

export const zGetApiV1DashboardData = z.object({
    body: z.optional(z.never()),
    path: z.optional(z.never()),
    query: z.optional(z.never())
});

export const zGetApiV1NotificationsData = z.object({
    body: z.optional(z.never()),
    path: z.optional(z.never()),
    query: z.optional(z.object({
        typeFilter: z.optional(z.string()).default('All'),
        statusFilter: z.optional(z.string()).default('All'),
        search: z.optional(z.string()).default(null),
        page: z.optional(z.int().min(-2147483648, { error: 'Invalid value: Expected int32 to be >= -2147483648' }).max(2147483647, { error: 'Invalid value: Expected int32 to be <= 2147483647' })).default(1),
        pageSize: z.optional(z.int().min(-2147483648, { error: 'Invalid value: Expected int32 to be >= -2147483648' }).max(2147483647, { error: 'Invalid value: Expected int32 to be <= 2147483647' })).default(10)
    }))
});

export const zGetApiV1NotificationsUnreadCountData = z.object({
    body: z.optional(z.never()),
    path: z.optional(z.never()),
    query: z.optional(z.never())
});

export const zPutApiV1NotificationsByIdReadData = z.object({
    body: z.optional(z.never()),
    path: z.object({
        id: z.int().min(-2147483648, { error: 'Invalid value: Expected int32 to be >= -2147483648' }).max(2147483647, { error: 'Invalid value: Expected int32 to be <= 2147483647' })
    }),
    query: z.optional(z.never())
});

export const zPutApiV1NotificationsReadAllData = z.object({
    body: z.optional(z.never()),
    path: z.optional(z.never()),
    query: z.optional(z.never())
});

export const zGetApiV1PetsData = z.object({
    body: z.optional(z.never()),
    path: z.optional(z.never()),
    query: z.optional(z.never())
});

export const zPostApiV1PetsData = z.object({
    body: z.object({
        Name: z.optional(z.string().min(0).max(100)),
        Type: z.optional(z.string().min(0).max(100)),
        Breed: z.optional(z.string().min(0).max(100)),
        Birthdate: z.optional(z.iso.datetime()),
        Photo: z.optional(zIFormFile)
    }),
    path: z.optional(z.never()),
    query: z.optional(z.never())
});

export const zGetApiV1PetsByIdData = z.object({
    body: z.optional(z.never()),
    path: z.object({
        id: z.int().min(-2147483648, { error: 'Invalid value: Expected int32 to be >= -2147483648' }).max(2147483647, { error: 'Invalid value: Expected int32 to be <= 2147483647' })
    }),
    query: z.optional(z.object({
        page: z.optional(z.int().min(-2147483648, { error: 'Invalid value: Expected int32 to be >= -2147483648' }).max(2147483647, { error: 'Invalid value: Expected int32 to be <= 2147483647' })).default(1),
        pageSize: z.optional(z.int().min(-2147483648, { error: 'Invalid value: Expected int32 to be >= -2147483648' }).max(2147483647, { error: 'Invalid value: Expected int32 to be <= 2147483647' })).default(5),
        search: z.optional(z.string()).default(null),
        categoryFilter: z.optional(z.int().min(-2147483648, { error: 'Invalid value: Expected int32 to be >= -2147483648' }).max(2147483647, { error: 'Invalid value: Expected int32 to be <= 2147483647' })).default(null)
    }))
});

export const zPutApiV1PetsByIdData = z.object({
    body: z.object({
        Name: z.optional(z.string().min(0).max(100)),
        Type: z.optional(z.string().min(0).max(100)),
        Breed: z.optional(z.string().min(0).max(100)),
        Birthdate: z.optional(z.iso.datetime()),
        Photo: z.optional(zIFormFile)
    }),
    path: z.object({
        id: z.int().min(-2147483648, { error: 'Invalid value: Expected int32 to be >= -2147483648' }).max(2147483647, { error: 'Invalid value: Expected int32 to be <= 2147483647' })
    }),
    query: z.optional(z.never())
});

export const zGetApiV1PetsBreedsData = z.object({
    body: z.optional(z.never()),
    path: z.optional(z.never()),
    query: z.optional(z.object({
        type: z.optional(z.string())
    }))
});

export const zGetApiV1PetsByIdCardData = z.object({
    body: z.optional(z.never()),
    path: z.object({
        id: z.int().min(-2147483648, { error: 'Invalid value: Expected int32 to be >= -2147483648' }).max(2147483647, { error: 'Invalid value: Expected int32 to be <= 2147483647' })
    }),
    query: z.optional(z.object({
        page: z.optional(z.int().min(-2147483648, { error: 'Invalid value: Expected int32 to be >= -2147483648' }).max(2147483647, { error: 'Invalid value: Expected int32 to be <= 2147483647' })).default(1),
        pageSize: z.optional(z.int().min(-2147483648, { error: 'Invalid value: Expected int32 to be >= -2147483648' }).max(2147483647, { error: 'Invalid value: Expected int32 to be <= 2147483647' })).default(12)
    }))
});

export const zGetApiV1PetsByIdCardPdfData = z.object({
    body: z.optional(z.never()),
    path: z.object({
        id: z.int().min(-2147483648, { error: 'Invalid value: Expected int32 to be >= -2147483648' }).max(2147483647, { error: 'Invalid value: Expected int32 to be <= 2147483647' })
    }),
    query: z.optional(z.never())
});

export const zGetApiV1ProfileData = z.object({
    body: z.optional(z.never()),
    path: z.optional(z.never()),
    query: z.optional(z.never())
});

export const zPutApiV1ProfileData = z.object({
    body: zUpdateProfileRequest,
    path: z.optional(z.never()),
    query: z.optional(z.never())
});

export const zPutApiV1ProfilePasswordData = z.object({
    body: zChangePasswordRequest,
    path: z.optional(z.never()),
    query: z.optional(z.never())
});

export const zPutApiV1ProfilePhotoData = z.object({
    body: z.object({
        photo: z.optional(zIFormFile)
    }),
    path: z.optional(z.never()),
    query: z.optional(z.never())
});
