// This file is auto-generated by @hey-api/openapi-ts

import * as z from 'zod';

export const zApiErrorResponse = z.object({
    success: z.optional(z.boolean()),
    message: z.optional(z.string()),
    errors: z.optional(z.union([
        z.record(z.string(), z.array(z.string())),
        z.null()
    ]))
});

export const zApiResponse = z.object({
    success: z.optional(z.boolean()),
    message: z.optional(z.union([
        z.string(),
        z.null()
    ]))
});

export const zApiResponseOfListOfstring = z.object({
    success: z.optional(z.boolean()),
    message: z.optional(z.union([
        z.string(),
        z.null()
    ])),
    data: z.optional(z.union([
        z.array(z.string()),
        z.null()
    ]))
});

export const zAppointmentListItemDto = z.object({
    appointmentId: z.optional(z.int().min(-2147483648, { error: 'Invalid value: Expected int32 to be >= -2147483648' }).max(2147483647, { error: 'Invalid value: Expected int32 to be <= 2147483647' })),
    appointmentDate: z.optional(z.iso.datetime()),
    status: z.optional(z.string()),
    groupId: z.optional(z.union([
        z.int().min(-2147483648, { error: 'Invalid value: Expected int32 to be >= -2147483648' }).max(2147483647, { error: 'Invalid value: Expected int32 to be <= 2147483647' }),
        z.null()
    ])),
    notes: z.optional(z.union([
        z.string(),
        z.null()
    ])),
    petId: z.optional(z.int().min(-2147483648, { error: 'Invalid value: Expected int32 to be >= -2147483648' }).max(2147483647, { error: 'Invalid value: Expected int32 to be <= 2147483647' })),
    petName: z.optional(z.string()),
    serviceType: z.optional(z.union([
        z.string(),
        z.null()
    ])),
    serviceSubtype: z.optional(z.union([
        z.string(),
        z.null()
    ])),
    isOwnAppointment: z.optional(z.boolean())
});

export const zApiResponseOfListOfAppointmentListItemDto = z.object({
    success: z.optional(z.boolean()),
    message: z.optional(z.union([
        z.string(),
        z.null()
    ])),
    data: z.optional(z.union([
        z.array(zAppointmentListItemDto),
        z.null()
    ]))
});

export const zBulkAppointmentItemRequest = z.object({
    petId: z.int().min(-2147483648, { error: 'Invalid value: Expected int32 to be >= -2147483648' }).max(2147483647, { error: 'Invalid value: Expected int32 to be <= 2147483647' }),
    categoryId: z.int().min(-2147483648, { error: 'Invalid value: Expected int32 to be >= -2147483648' }).max(2147483647, { error: 'Invalid value: Expected int32 to be <= 2147483647' }),
    subtypeId: z.optional(z.union([
        z.int().min(-2147483648, { error: 'Invalid value: Expected int32 to be >= -2147483648' }).max(2147483647, { error: 'Invalid value: Expected int32 to be <= 2147483647' }),
        z.null()
    ])),
    appointmentDate: z.iso.datetime(),
    appointmentTime: z.string(),
    notes: z.optional(z.union([
        z.string(),
        z.null()
    ]))
});

export const zBulkAppointmentResponse = z.union([
    z.object({
        groupId: z.optional(z.int().min(-2147483648, { error: 'Invalid value: Expected int32 to be >= -2147483648' }).max(2147483647, { error: 'Invalid value: Expected int32 to be <= 2147483647' })),
        count: z.optional(z.int().min(-2147483648, { error: 'Invalid value: Expected int32 to be >= -2147483648' }).max(2147483647, { error: 'Invalid value: Expected int32 to be <= 2147483647' }))
    }),
    z.null()
]);

export const zApiResponseOfBulkAppointmentResponse = z.object({
    success: z.optional(z.boolean()),
    message: z.optional(z.union([
        z.string(),
        z.null()
    ])),
    data: z.optional(zBulkAppointmentResponse)
});

export const zChangePasswordRequest = z.object({
    currentPassword: z.string(),
    newPassword: z.string().min(8),
    confirmPassword: z.string()
});

export const zCreateAppointmentRequest = z.object({
    petId: z.int().min(-2147483648, { error: 'Invalid value: Expected int32 to be >= -2147483648' }).max(2147483647, { error: 'Invalid value: Expected int32 to be <= 2147483647' }),
    categoryId: z.int().min(-2147483648, { error: 'Invalid value: Expected int32 to be >= -2147483648' }).max(2147483647, { error: 'Invalid value: Expected int32 to be <= 2147483647' }),
    subtypeId: z.optional(z.union([
        z.int().min(-2147483648, { error: 'Invalid value: Expected int32 to be >= -2147483648' }).max(2147483647, { error: 'Invalid value: Expected int32 to be <= 2147483647' }),
        z.null()
    ])),
    appointmentDate: z.iso.datetime(),
    appointmentTime: z.string(),
    notes: z.optional(z.union([
        z.string(),
        z.null()
    ]))
});

export const zCreateBulkAppointmentRequest = z.object({
    appointments: z.array(zBulkAppointmentItemRequest).min(1)
});

export const zDashboardAppointmentDto = z.object({
    appointmentId: z.optional(z.int().min(-2147483648, { error: 'Invalid value: Expected int32 to be >= -2147483648' }).max(2147483647, { error: 'Invalid value: Expected int32 to be <= 2147483647' })),
    appointmentDate: z.optional(z.iso.datetime()),
    status: z.optional(z.string()),
    petId: z.optional(z.int().min(-2147483648, { error: 'Invalid value: Expected int32 to be >= -2147483648' }).max(2147483647, { error: 'Invalid value: Expected int32 to be <= 2147483647' })),
    petName: z.optional(z.string()),
    serviceType: z.optional(z.union([
        z.string(),
        z.null()
    ]))
});

export const zDashboardDewormDueDto = z.object({
    appointmentId: z.optional(z.int().min(-2147483648, { error: 'Invalid value: Expected int32 to be >= -2147483648' }).max(2147483647, { error: 'Invalid value: Expected int32 to be <= 2147483647' })),
    dueDate: z.optional(z.union([
        z.iso.datetime(),
        z.null()
    ])),
    petId: z.optional(z.int().min(-2147483648, { error: 'Invalid value: Expected int32 to be >= -2147483648' }).max(2147483647, { error: 'Invalid value: Expected int32 to be <= 2147483647' })),
    petName: z.optional(z.string()),
    serviceType: z.optional(z.union([
        z.string(),
        z.null()
    ]))
});

export const zDashboardPetDto = z.object({
    petId: z.optional(z.int().min(-2147483648, { error: 'Invalid value: Expected int32 to be >= -2147483648' }).max(2147483647, { error: 'Invalid value: Expected int32 to be <= 2147483647' })),
    name: z.optional(z.string()),
    breed: z.optional(z.string()),
    photoUrl: z.optional(z.union([
        z.string(),
        z.null()
    ])),
    birthdate: z.optional(z.iso.datetime())
});

export const zDashboardVaccineDueDto = z.object({
    appointmentId: z.optional(z.int().min(-2147483648, { error: 'Invalid value: Expected int32 to be >= -2147483648' }).max(2147483647, { error: 'Invalid value: Expected int32 to be <= 2147483647' })),
    dueDate: z.optional(z.union([
        z.iso.datetime(),
        z.null()
    ])),
    petId: z.optional(z.int().min(-2147483648, { error: 'Invalid value: Expected int32 to be >= -2147483648' }).max(2147483647, { error: 'Invalid value: Expected int32 to be <= 2147483647' })),
    petName: z.optional(z.string()),
    serviceType: z.optional(z.union([
        z.string(),
        z.null()
    ]))
});

export const zDashboardResponse = z.union([
    z.object({
        userName: z.optional(z.string()),
        pets: z.optional(z.array(zDashboardPetDto)),
        upcomingAppointments: z.optional(z.array(zDashboardAppointmentDto)),
        vaccineDue: z.optional(z.array(zDashboardVaccineDueDto)),
        dewormDue: z.optional(z.array(zDashboardDewormDueDto))
    }),
    z.null()
]);

export const zApiResponseOfDashboardResponse = z.object({
    success: z.optional(z.boolean()),
    message: z.optional(z.union([
        z.string(),
        z.null()
    ])),
    data: z.optional(zDashboardResponse)
});

export const zForgotPasswordRequest = z.object({
    email: z.string()
});

export const zIFormFile = z.string();

export const zLoginRequest = z.object({
    email: z.string(),
    password: z.string(),
    deviceInfo: z.optional(z.union([
        z.string(),
        z.null()
    ]))
});

export const zNotificationDto = z.object({
    notificationId: z.optional(z.int().min(-2147483648, { error: 'Invalid value: Expected int32 to be >= -2147483648' }).max(2147483647, { error: 'Invalid value: Expected int32 to be <= 2147483647' })),
    message: z.optional(z.string()),
    type: z.optional(z.string()),
    createdAt: z.optional(z.iso.datetime()),
    isRead: z.optional(z.boolean()),
    redirectUrl: z.optional(z.union([
        z.string(),
        z.null()
    ]))
});

export const zNotificationListResponse = z.object({
    unreadCount: z.optional(z.int().min(-2147483648, { error: 'Invalid value: Expected int32 to be >= -2147483648' }).max(2147483647, { error: 'Invalid value: Expected int32 to be <= 2147483647' })),
    success: z.optional(z.boolean()),
    items: z.optional(z.array(zNotificationDto)),
    currentPage: z.optional(z.int().min(-2147483648, { error: 'Invalid value: Expected int32 to be >= -2147483648' }).max(2147483647, { error: 'Invalid value: Expected int32 to be <= 2147483647' })),
    totalPages: z.optional(z.int().min(-2147483648, { error: 'Invalid value: Expected int32 to be >= -2147483648' }).max(2147483647, { error: 'Invalid value: Expected int32 to be <= 2147483647' })),
    totalCount: z.optional(z.int().min(-2147483648, { error: 'Invalid value: Expected int32 to be >= -2147483648' }).max(2147483647, { error: 'Invalid value: Expected int32 to be <= 2147483647' })),
    pageSize: z.optional(z.int().min(-2147483648, { error: 'Invalid value: Expected int32 to be >= -2147483648' }).max(2147483647, { error: 'Invalid value: Expected int32 to be <= 2147483647' })),
    hasPrevious: z.optional(z.boolean()),
    hasNext: z.optional(z.boolean())
});

export const zOwnerBasicDto = z.union([
    z.object({
        userId: z.optional(z.int().min(-2147483648, { error: 'Invalid value: Expected int32 to be >= -2147483648' }).max(2147483647, { error: 'Invalid value: Expected int32 to be <= 2147483647' })),
        ownerId: z.optional(z.int().min(-2147483648, { error: 'Invalid value: Expected int32 to be >= -2147483648' }).max(2147483647, { error: 'Invalid value: Expected int32 to be <= 2147483647' })),
        firstName: z.optional(z.string()),
        lastName: z.optional(z.string()),
        email: z.optional(z.string()),
        profileImage: z.optional(z.union([
            z.string(),
            z.null()
        ]))
    }),
    z.null()
]);

export const zLoginResponse = z.union([
    z.object({
        requires2FA: z.optional(z.boolean()),
        twoFactorUserId: z.optional(z.union([
            z.int().min(-2147483648, { error: 'Invalid value: Expected int32 to be >= -2147483648' }).max(2147483647, { error: 'Invalid value: Expected int32 to be <= 2147483647' }),
            z.null()
        ])),
        accessToken: z.optional(z.union([
            z.string(),
            z.null()
        ])),
        refreshToken: z.optional(z.union([
            z.string(),
            z.null()
        ])),
        expiresAt: z.optional(z.union([
            z.iso.datetime(),
            z.null()
        ])),
        owner: z.optional(zOwnerBasicDto)
    }),
    z.null()
]);

export const zApiResponseOfLoginResponse = z.object({
    success: z.optional(z.boolean()),
    message: z.optional(z.union([
        z.string(),
        z.null()
    ])),
    data: z.optional(zLoginResponse)
});

export const zPetCardRecordDto = z.object({
    appointmentId: z.optional(z.int().min(-2147483648, { error: 'Invalid value: Expected int32 to be >= -2147483648' }).max(2147483647, { error: 'Invalid value: Expected int32 to be <= 2147483647' })),
    appointmentDate: z.optional(z.iso.datetime()),
    notes: z.optional(z.union([
        z.string(),
        z.null()
    ])),
    serviceType: z.optional(z.union([
        z.string(),
        z.null()
    ])),
    serviceSubtype: z.optional(z.union([
        z.string(),
        z.null()
    ])),
    administeredBy: z.optional(z.union([
        z.string(),
        z.null()
    ])),
    dueDate: z.optional(z.union([
        z.iso.datetime(),
        z.null()
    ]))
});

export const zPetDetailDto = z.union([
    z.object({
        petId: z.optional(z.int().min(-2147483648, { error: 'Invalid value: Expected int32 to be >= -2147483648' }).max(2147483647, { error: 'Invalid value: Expected int32 to be <= 2147483647' })),
        name: z.optional(z.string()),
        type: z.optional(z.string()),
        breed: z.optional(z.string()),
        birthdate: z.optional(z.iso.datetime()),
        photoUrl: z.optional(z.union([
            z.string(),
            z.null()
        ])),
        age: z.optional(z.string()),
        ownerName: z.optional(z.string())
    }),
    z.null()
]);

export const zApiResponseOfPetDetailDto = z.object({
    success: z.optional(z.boolean()),
    message: z.optional(z.union([
        z.string(),
        z.null()
    ])),
    data: z.optional(zPetDetailDto)
});

export const zPetListItemDto = z.object({
    petId: z.optional(z.int().min(-2147483648, { error: 'Invalid value: Expected int32 to be >= -2147483648' }).max(2147483647, { error: 'Invalid value: Expected int32 to be <= 2147483647' })),
    name: z.optional(z.string()),
    type: z.optional(z.string()),
    breed: z.optional(z.string()),
    birthdate: z.optional(z.iso.datetime()),
    photoUrl: z.optional(z.union([
        z.string(),
        z.null()
    ])),
    age: z.optional(z.string()),
    createdAt: z.optional(z.iso.datetime())
});

export const zApiResponseOfListOfPetListItemDto = z.object({
    success: z.optional(z.boolean()),
    message: z.optional(z.union([
        z.string(),
        z.null()
    ])),
    data: z.optional(z.union([
        z.array(zPetListItemDto),
        z.null()
    ]))
});

export const zPetCardResponse = z.union([
    z.object({
        pet: z.optional(zPetListItemDto),
        ownerName: z.optional(z.string()),
        ownerPhone: z.optional(z.string()),
        ownerEmail: z.optional(z.string()),
        ageInMonths: z.optional(z.int().min(-2147483648, { error: 'Invalid value: Expected int32 to be >= -2147483648' }).max(2147483647, { error: 'Invalid value: Expected int32 to be <= 2147483647' })),
        records: z.optional(z.array(zPetCardRecordDto)),
        currentPage: z.optional(z.int().min(-2147483648, { error: 'Invalid value: Expected int32 to be >= -2147483648' }).max(2147483647, { error: 'Invalid value: Expected int32 to be <= 2147483647' })),
        totalPages: z.optional(z.int().min(-2147483648, { error: 'Invalid value: Expected int32 to be >= -2147483648' }).max(2147483647, { error: 'Invalid value: Expected int32 to be <= 2147483647' })),
        totalRecords: z.optional(z.int().min(-2147483648, { error: 'Invalid value: Expected int32 to be >= -2147483648' }).max(2147483647, { error: 'Invalid value: Expected int32 to be <= 2147483647' }))
    }),
    z.null()
]);

export const zApiResponseOfPetCardResponse = z.object({
    success: z.optional(z.boolean()),
    message: z.optional(z.union([
        z.string(),
        z.null()
    ])),
    data: z.optional(zPetCardResponse)
});

export const zPetListItemDto2 = z.union([
    z.object({
        petId: z.optional(z.int().min(-2147483648, { error: 'Invalid value: Expected int32 to be >= -2147483648' }).max(2147483647, { error: 'Invalid value: Expected int32 to be <= 2147483647' })),
        name: z.optional(z.string()),
        type: z.optional(z.string()),
        breed: z.optional(z.string()),
        birthdate: z.optional(z.iso.datetime()),
        photoUrl: z.optional(z.union([
            z.string(),
            z.null()
        ])),
        age: z.optional(z.string()),
        createdAt: z.optional(z.iso.datetime())
    }),
    z.null()
]);

export const zApiResponseOfPetListItemDto = z.object({
    success: z.optional(z.boolean()),
    message: z.optional(z.union([
        z.string(),
        z.null()
    ])),
    data: z.optional(zPetListItemDto2)
});

export const zProfileResponse = z.union([
    z.object({
        userId: z.optional(z.int().min(-2147483648, { error: 'Invalid value: Expected int32 to be >= -2147483648' }).max(2147483647, { error: 'Invalid value: Expected int32 to be <= 2147483647' })),
        ownerId: z.optional(z.int().min(-2147483648, { error: 'Invalid value: Expected int32 to be >= -2147483648' }).max(2147483647, { error: 'Invalid value: Expected int32 to be <= 2147483647' })),
        firstName: z.optional(z.string()),
        lastName: z.optional(z.string()),
        email: z.optional(z.string()),
        phone: z.optional(z.union([
            z.string(),
            z.null()
        ])),
        profileImageUrl: z.optional(z.union([
            z.string(),
            z.null()
        ])),
        createdAt: z.optional(z.iso.datetime())
    }),
    z.null()
]);

export const zApiResponseOfProfileResponse = z.object({
    success: z.optional(z.boolean()),
    message: z.optional(z.union([
        z.string(),
        z.null()
    ])),
    data: z.optional(zProfileResponse)
});

export const zRefreshTokenRequest = z.object({
    refreshToken: z.string()
});

export const zRegisterRequest = z.object({
    firstName: z.string().min(0).max(50),
    lastName: z.string().min(0).max(50),
    email: z.string(),
    phone: z.string().regex(/^\d{11}$/),
    password: z.string().min(8),
    confirmPassword: z.string()
});

export const zResetPasswordRequest = z.object({
    token: z.string(),
    newPassword: z.string().min(8),
    confirmPassword: z.string()
});

export const zServiceSubtypeDto = z.object({
    subtypeId: z.optional(z.int().min(-2147483648, { error: 'Invalid value: Expected int32 to be >= -2147483648' }).max(2147483647, { error: 'Invalid value: Expected int32 to be <= 2147483647' })),
    serviceSubType: z.optional(z.string())
});

export const zServiceCategoryDto = z.object({
    categoryId: z.optional(z.int().min(-2147483648, { error: 'Invalid value: Expected int32 to be >= -2147483648' }).max(2147483647, { error: 'Invalid value: Expected int32 to be <= 2147483647' })),
    serviceType: z.optional(z.string()),
    subtypes: z.optional(z.array(zServiceSubtypeDto))
});

export const zApiResponseOfListOfServiceCategoryDto = z.object({
    success: z.optional(z.boolean()),
    message: z.optional(z.union([
        z.string(),
        z.null()
    ])),
    data: z.optional(z.union([
        z.array(zServiceCategoryDto),
        z.null()
    ]))
});

export const zTimeSlotDto = z.object({
    time: z.optional(z.string()),
    available: z.optional(z.boolean())
});

export const zTimeSlotsResponse = z.union([
    z.object({
        date: z.optional(z.string()),
        slots: z.optional(z.array(zTimeSlotDto))
    }),
    z.null()
]);

export const zApiResponseOfTimeSlotsResponse = z.object({
    success: z.optional(z.boolean()),
    message: z.optional(z.union([
        z.string(),
        z.null()
    ])),
    data: z.optional(zTimeSlotsResponse)
});

export const zTokenResponse = z.union([
    z.object({
        accessToken: z.optional(z.string()),
        refreshToken: z.optional(z.string()),
        expiresAt: z.optional(z.iso.datetime()),
        owner: z.optional(zOwnerBasicDto)
    }),
    z.null()
]);

export const zApiResponseOfTokenResponse = z.object({
    success: z.optional(z.boolean()),
    message: z.optional(z.union([
        z.string(),
        z.null()
    ])),
    data: z.optional(zTokenResponse)
});

export const zUnreadCountResponse = z.union([
    z.object({
        unreadCount: z.optional(z.int().min(-2147483648, { error: 'Invalid value: Expected int32 to be >= -2147483648' }).max(2147483647, { error: 'Invalid value: Expected int32 to be <= 2147483647' }))
    }),
    z.null()
]);

export const zApiResponseOfUnreadCountResponse = z.object({
    success: z.optional(z.boolean()),
    message: z.optional(z.union([
        z.string(),
        z.null()
    ])),
    data: z.optional(zUnreadCountResponse)
});

export const zUpdatePhotoResponse = z.union([
    z.object({
        profileImageUrl: z.optional(z.string())
    }),
    z.null()
]);

export const zApiResponseOfUpdatePhotoResponse = z.object({
    success: z.optional(z.boolean()),
    message: z.optional(z.union([
        z.string(),
        z.null()
    ])),
    data: z.optional(zUpdatePhotoResponse)
});

export const zUpdateProfileRequest = z.object({
    firstName: z.string().min(0).max(50),
    lastName: z.string().min(0).max(50),
    phone: z.string().regex(/^\d{11}$/)
});

export const zVerify2FaRequest = z.object({
    userId: z.int().min(-2147483648, { error: 'Invalid value: Expected int32 to be >= -2147483648' }).max(2147483647, { error: 'Invalid value: Expected int32 to be <= 2147483647' }),
    code: z.string().length(6),
    deviceInfo: z.optional(z.union([
        z.string(),
        z.null()
    ]))
});

export const zGetApiV1AppointmentsData = z.object({
    body: z.optional(z.never()),
    path: z.optional(z.never()),
    query: z.optional(z.never())
});

/**
 * OK
 */
export const zGetApiV1AppointmentsResponse = zApiResponseOfListOfAppointmentListItemDto;

export const zPostApiV1AppointmentsData = z.object({
    body: zCreateAppointmentRequest,
    path: z.optional(z.never()),
    query: z.optional(z.never())
});

/**
 * Created
 */
export const zPostApiV1AppointmentsResponse = zApiResponse;

export const zPostApiV1AppointmentsBulkData = z.object({
    body: zCreateBulkAppointmentRequest,
    path: z.optional(z.never()),
    query: z.optional(z.never())
});

/**
 * Created
 */
export const zPostApiV1AppointmentsBulkResponse = zApiResponseOfBulkAppointmentResponse;

export const zPostApiV1AppointmentsByIdCancelData = z.object({
    body: z.optional(z.never()),
    path: z.object({
        id: z.int().min(-2147483648, { error: 'Invalid value: Expected int32 to be >= -2147483648' }).max(2147483647, { error: 'Invalid value: Expected int32 to be <= 2147483647' })
    }),
    query: z.optional(z.never())
});

/**
 * OK
 */
export const zPostApiV1AppointmentsByIdCancelResponse = zApiResponse;

export const zGetApiV1AppointmentsTimeSlotsData = z.object({
    body: z.optional(z.never()),
    path: z.optional(z.never()),
    query: z.optional(z.object({
        date: z.optional(z.iso.datetime())
    }))
});

/**
 * OK
 */
export const zGetApiV1AppointmentsTimeSlotsResponse = zApiResponseOfTimeSlotsResponse;

export const zGetApiV1AppointmentsServicesData = z.object({
    body: z.optional(z.never()),
    path: z.optional(z.never()),
    query: z.optional(z.never())
});

/**
 * OK
 */
export const zGetApiV1AppointmentsServicesResponse = zApiResponseOfListOfServiceCategoryDto;

export const zPostApiV1AuthLoginData = z.object({
    body: zLoginRequest,
    path: z.optional(z.never()),
    query: z.optional(z.never())
});

/**
 * OK
 */
export const zPostApiV1AuthLoginResponse = zApiResponseOfLoginResponse;

export const zPostApiV1AuthVerify2FaData = z.object({
    body: zVerify2FaRequest,
    path: z.optional(z.never()),
    query: z.optional(z.never())
});

/**
 * OK
 */
export const zPostApiV1AuthVerify2FaResponse = zApiResponseOfTokenResponse;

export const zPostApiV1AuthRegisterData = z.object({
    body: zRegisterRequest,
    path: z.optional(z.never()),
    query: z.optional(z.never())
});

/**
 * Created
 */
export const zPostApiV1AuthRegisterResponse = zApiResponse;

export const zPostApiV1AuthRefreshData = z.object({
    body: zRefreshTokenRequest,
    path: z.optional(z.never()),
    query: z.optional(z.never())
});

/**
 * OK
 */
export const zPostApiV1AuthRefreshResponse = zApiResponseOfTokenResponse;

export const zPostApiV1AuthLogoutData = z.object({
    body: zRefreshTokenRequest,
    path: z.optional(z.never()),
    query: z.optional(z.never())
});

/**
 * OK
 */
export const zPostApiV1AuthLogoutResponse = zApiResponse;

export const zPostApiV1AuthForgotPasswordData = z.object({
    body: zForgotPasswordRequest,
    path: z.optional(z.never()),
    query: z.optional(z.never())
});

/**
 * OK
 */
export const zPostApiV1AuthForgotPasswordResponse = zApiResponse;

export const zPostApiV1AuthResetPasswordData = z.object({
    body: zResetPasswordRequest,
    path: z.optional(z.never()),
    query: z.optional(z.never())
});

/**
 * OK
 */
export const zPostApiV1AuthResetPasswordResponse = zApiResponse;

export const zGetApiV1DashboardData = z.object({
    body: z.optional(z.never()),
    path: z.optional(z.never()),
    query: z.optional(z.never())
});

/**
 * OK
 */
export const zGetApiV1DashboardResponse = zApiResponseOfDashboardResponse;

export const zGetApiV1NotificationsData = z.object({
    body: z.optional(z.never()),
    path: z.optional(z.never()),
    query: z.optional(z.object({
        typeFilter: z.optional(z.string()).default('All'),
        statusFilter: z.optional(z.string()).default('All'),
        search: z.optional(z.string()).default(null),
        page: z.optional(z.int().min(-2147483648, { error: 'Invalid value: Expected int32 to be >= -2147483648' }).max(2147483647, { error: 'Invalid value: Expected int32 to be <= 2147483647' })).default(1),
        pageSize: z.optional(z.int().min(-2147483648, { error: 'Invalid value: Expected int32 to be >= -2147483648' }).max(2147483647, { error: 'Invalid value: Expected int32 to be <= 2147483647' })).default(10)
    }))
});

/**
 * OK
 */
export const zGetApiV1NotificationsResponse = zNotificationListResponse;

export const zGetApiV1NotificationsUnreadCountData = z.object({
    body: z.optional(z.never()),
    path: z.optional(z.never()),
    query: z.optional(z.never())
});

/**
 * OK
 */
export const zGetApiV1NotificationsUnreadCountResponse = zApiResponseOfUnreadCountResponse;

export const zPutApiV1NotificationsByIdReadData = z.object({
    body: z.optional(z.never()),
    path: z.object({
        id: z.int().min(-2147483648, { error: 'Invalid value: Expected int32 to be >= -2147483648' }).max(2147483647, { error: 'Invalid value: Expected int32 to be <= 2147483647' })
    }),
    query: z.optional(z.never())
});

/**
 * OK
 */
export const zPutApiV1NotificationsByIdReadResponse = zApiResponse;

export const zPutApiV1NotificationsReadAllData = z.object({
    body: z.optional(z.never()),
    path: z.optional(z.never()),
    query: z.optional(z.never())
});

/**
 * OK
 */
export const zPutApiV1NotificationsReadAllResponse = zApiResponse;

export const zGetApiV1PetsData = z.object({
    body: z.optional(z.never()),
    path: z.optional(z.never()),
    query: z.optional(z.never())
});

/**
 * OK
 */
export const zGetApiV1PetsResponse = zApiResponseOfListOfPetListItemDto;

export const zPostApiV1PetsData = z.object({
    body: z.object({
        Name: z.optional(z.string().min(0).max(100)),
        Type: z.optional(z.string().min(0).max(100)),
        Breed: z.optional(z.string().min(0).max(100)),
        Birthdate: z.optional(z.iso.datetime()),
        Photo: z.optional(zIFormFile)
    }),
    path: z.optional(z.never()),
    query: z.optional(z.never())
});

/**
 * Created
 */
export const zPostApiV1PetsResponse = zApiResponseOfPetListItemDto;

export const zGetApiV1PetsByIdData = z.object({
    body: z.optional(z.never()),
    path: z.object({
        id: z.int().min(-2147483648, { error: 'Invalid value: Expected int32 to be >= -2147483648' }).max(2147483647, { error: 'Invalid value: Expected int32 to be <= 2147483647' })
    }),
    query: z.optional(z.object({
        page: z.optional(z.int().min(-2147483648, { error: 'Invalid value: Expected int32 to be >= -2147483648' }).max(2147483647, { error: 'Invalid value: Expected int32 to be <= 2147483647' })).default(1),
        pageSize: z.optional(z.int().min(-2147483648, { error: 'Invalid value: Expected int32 to be >= -2147483648' }).max(2147483647, { error: 'Invalid value: Expected int32 to be <= 2147483647' })).default(5),
        search: z.optional(z.string()).default(null),
        categoryFilter: z.optional(z.int().min(-2147483648, { error: 'Invalid value: Expected int32 to be >= -2147483648' }).max(2147483647, { error: 'Invalid value: Expected int32 to be <= 2147483647' })).default(null)
    }))
});

/**
 * OK
 */
export const zGetApiV1PetsByIdResponse = zApiResponseOfPetDetailDto;

export const zPutApiV1PetsByIdData = z.object({
    body: z.object({
        Name: z.optional(z.string().min(0).max(100)),
        Type: z.optional(z.string().min(0).max(100)),
        Breed: z.optional(z.string().min(0).max(100)),
        Birthdate: z.optional(z.iso.datetime()),
        Photo: z.optional(zIFormFile)
    }),
    path: z.object({
        id: z.int().min(-2147483648, { error: 'Invalid value: Expected int32 to be >= -2147483648' }).max(2147483647, { error: 'Invalid value: Expected int32 to be <= 2147483647' })
    }),
    query: z.optional(z.never())
});

/**
 * OK
 */
export const zPutApiV1PetsByIdResponse = zApiResponseOfPetListItemDto;

export const zGetApiV1PetsBreedsData = z.object({
    body: z.optional(z.never()),
    path: z.optional(z.never()),
    query: z.optional(z.object({
        type: z.optional(z.string())
    }))
});

/**
 * OK
 */
export const zGetApiV1PetsBreedsResponse = zApiResponseOfListOfstring;

export const zGetApiV1PetsByIdCardData = z.object({
    body: z.optional(z.never()),
    path: z.object({
        id: z.int().min(-2147483648, { error: 'Invalid value: Expected int32 to be >= -2147483648' }).max(2147483647, { error: 'Invalid value: Expected int32 to be <= 2147483647' })
    }),
    query: z.optional(z.object({
        page: z.optional(z.int().min(-2147483648, { error: 'Invalid value: Expected int32 to be >= -2147483648' }).max(2147483647, { error: 'Invalid value: Expected int32 to be <= 2147483647' })).default(1),
        pageSize: z.optional(z.int().min(-2147483648, { error: 'Invalid value: Expected int32 to be >= -2147483648' }).max(2147483647, { error: 'Invalid value: Expected int32 to be <= 2147483647' })).default(12)
    }))
});

/**
 * OK
 */
export const zGetApiV1PetsByIdCardResponse = zApiResponseOfPetCardResponse;

export const zGetApiV1PetsByIdCardPdfData = z.object({
    body: z.optional(z.never()),
    path: z.object({
        id: z.int().min(-2147483648, { error: 'Invalid value: Expected int32 to be >= -2147483648' }).max(2147483647, { error: 'Invalid value: Expected int32 to be <= 2147483647' })
    }),
    query: z.optional(z.never())
});

/**
 * OK
 */
export const zGetApiV1PetsByIdCardPdfResponse = z.string();

export const zGetApiV1ProfileData = z.object({
    body: z.optional(z.never()),
    path: z.optional(z.never()),
    query: z.optional(z.never())
});

/**
 * OK
 */
export const zGetApiV1ProfileResponse = zApiResponseOfProfileResponse;

export const zPutApiV1ProfileData = z.object({
    body: zUpdateProfileRequest,
    path: z.optional(z.never()),
    query: z.optional(z.never())
});

/**
 * OK
 */
export const zPutApiV1ProfileResponse = zApiResponse;

export const zPutApiV1ProfilePasswordData = z.object({
    body: zChangePasswordRequest,
    path: z.optional(z.never()),
    query: z.optional(z.never())
});

/**
 * OK
 */
export const zPutApiV1ProfilePasswordResponse = zApiResponse;

export const zPutApiV1ProfilePhotoData = z.object({
    body: z.object({
        photo: z.optional(zIFormFile)
    }),
    path: z.optional(z.never()),
    query: z.optional(z.never())
});

/**
 * OK
 */
export const zPutApiV1ProfilePhotoResponse = zApiResponseOfUpdatePhotoResponse;
